#!/bin/bash

case $BLOCK_BUTTON in
    4)  xbacklight -steps 1 -time 0 -dec 5 ;;
    5)  xbacklight -steps 1 -time 0 -inc 5 ;;
esac

BRIGHTNESS=$(cat /sys/class/backlight/*/brightness)
MAXBRIGHTNESS=$(cat /sys/class/backlight/*/max_brightness)

PERCENT=$(((BRIGHTNESS * 100 / MAXBRIGHTNESS + 3) / 5 * 5))

echo -ne "<span font='12'>\uf835</span>  $PERCENT%"
