#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
sysxprofile=/etc/xprofile

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
userxprofile=$HOME/.config/X11/xprofile


# merge in defaults and keymaps

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$sysxprofile" ] && . "$sysxprofile"

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userxprofile" ] && . "$userxprofile"

#[ -f /etc/xsession ] && . /etc/xsession
#[ -f ~/.xsession ] && . ~/.xsession

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

#echo "Starting at $(date)" >> ~/.i3/logfile
#exec /usr/bin/i3
# -V -d all >> ~/.i3/logfile 2>&1

# exec /usr/bin/dwm
exec /usr/local/bin/dwm
