#!/bin/sh

# Use neovim instead of vim
command -v nvim >/dev/null 2>&1 && \
    alias vim='nvim' vimdiff='nvim -d'

# Enable aliases to be sudo'ed
alias sudo='sudo '

# Commands should be more verbose
if [ "$(uname -s)" = Darwin ] ; then
    alias rm='rm -v'
else
    alias rm='rm -vI'
fi
alias cp='cp -iv'
alias mv='mv -iv'
alias bc='bc -lq'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'

# Colours are nice
if [ "$(uname -s)" = Darwin ] ; then
    alias ls='ls -G'
else
    alias ls='ls --color=auto --group-directories-first'
fi
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# TLDR
alias clip='clipboard-arg '
alias ka='killall'
alias nwsb='newsboat'
alias pm='pulsemixer'
alias rep='repeat-until '
alias spfm='spacefm'
alias tors='torsocks -i '
alias trem='transmission-remote'
alias ts='taskset 0xFFFFFFFE '
alias z='zathura'

alias ranger='[ -n "$RANGER_LEVEL" ] && exit || ranger'
