#!/bin/sh

# Use neovim instead of vim
if command -v nvim > /dev/null ; then
    alias vim='nvim'
    alias vimdiff='nvim -d'
fi

# Enable aliases to be sudo'ed
alias sudo='sudo '

# Commands should be more verbose
if [ "$(uname -s)" = Darwin ] ; then
    alias rm='rm -v'
else
    alias rm='timeout 3 rm -vI --one-file-system'
fi
alias cp='cp -iv'
alias ln='ln -i'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Commands should be less verbose
alias bc='bc -lq'
alias ffmpeg='ffmpeg -hide_banner'
alias ffprobe='ffprobe -hide_banner'

# Formatting is nice
if [ "$(uname -s)" = Darwin ] ; then
    alias ls='ls -G'
else
    alias ls='ls -hF --color=auto --group-directories-first'
fi
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# TLDR
alias clip='clipboard-arg '
alias ka='killall'
alias lctl='loginctl'
alias nwsb='newsboat'
alias pm='pulsemixer'
alias rep='repeat-until '
alias spfm='spacefm'
alias tors='torsocks -i '
alias trem='transmission-remote'
alias ts='taskset 0xFFFFFFFE '
alias z='zathura'

alias ranger='[ -n "$RANGER_LEVEL" ] && exit || ranger'

# stuff
alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME/nvidia/settings"'
