#!/bin/sh

if [ -s "$HOME"/.config/shell/env ] ; then
    . "$HOME"/.config/shell/env
fi

if [ -s "$HOME"/.config/shell/env.local ] ; then
    . "$HOME"/.config/shell/env.local
fi

if [ -z "$DISPLAY" ] && [ "$(tty)" = /dev/tty1 ] && command -v startx > /dev/null ; then
    startx "$XINITRC"
    exit
fi
