" Plugins {{{

" Airline {{{
let g:airline_theme = 'nord'
" }}}

" }}}
" General {{{

set cursorline

colorscheme nord

" }}}
" Options {{{

" Font
set guifont=Iosevka\ 14

" Gui options {{{

set guioptions-=m   " remove menu bar
set guioptions-=T   " remove tool bar
set guioptions-=r   " remove right scrollbar
set guioptions-=l   " remove left scrollbar

" }}}

" }}}
