" XDG compliant {{{

set undodir=$XDG_DATA_HOME/vim/undo
set backupdir=$XDG_DATA_HOME/vim/backup
set directory=$XDG_DATA_HOME/vim/swap
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

" }}}
" Pathogen {{{

set sessionoptions-=options
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
Helptags

" }}}
" Plugins {{{

" Vim-Latex {{{

set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
let g:Tex_SmartKeyQuote=0

imap <c-\> <Plug>IMAP_JumpForward
nmap <c-\> <Plug>IMAP_JumpForward
vmap <c-\> <Plug>IMAP_JumpForward
nmap <localleader>l :redraw!<cr>

" }}}

" Airline {{{

" Required
set laststatus=2
let g:airline_powerline_fonts = 1

let g:airline_skip_empty_sections = 1

" Theme
let g:airline_theme = 'luna'

" }}}

" bufferline {{{

let g:bufferline_echo = 0

" }}}

" Syntastic {{{

"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0

" }}}

" NERDTree {{{

nnoremap <C-n> :NERDTreeToggle<CR>

" }}}

" }}}
" General {{{

" Basic options {{{

set history=1000
set modelines=0
set hidden
set ruler
set showmode
set showcmd
set novisualbell
set backspace=indent,eol,start
set number
set relativenumber
set ttyfast
set lazyredraw
set showmatch
set matchtime=3
set shell=/bin/bash
set splitbelow
set splitright
set notimeout
set nottimeout
set shiftround
set autoread
set title
set linebreak
set mouse=a
set nojoinspaces

" }}}

colorscheme luna-term

syntax on
filetype plugin indent on
set modeline
set modelines=5

set encoding=utf-8
setglobal fileencoding=utf-8

set conceallevel=0

set foldmethod=marker

" Leader {{{

let mapleader = ","
let maplocalleader = "\\"

" }}}

inoremap <localleader>\ \\

command! W :w !sudo tee %

" }}}
" Options {{{

" Scrolling {{{

set scrolloff=3
set sidescroll=1
set sidescrolloff=10

" }}}

" Show invisible char {{{

set list
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮,trail:·
set showbreak=↪
hi NonText ctermfg=244
hi SpecialKey ctermfg=244

" }}}

" Tab, spaces, wrapping options {{{

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set wrap
set textwidth=120
set colorcolumn=+1
set formatoptions=qrn1

" }}}

" Wildmenu {{{

set wildmenu
set wildmode=list:longest

" Ignore
set wildignore+=*.aux,*.out,*.toc               " Latex
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg  " binary images
set wildignore+=*.sw?                           " Vim swap files
set wildignore+=*.DS_Store                      " OSX

" }}}

" Resize splits when the window is resized
au VimResized * exe "normal! \<c-w>="

" Line Return {{{

" Makes Vim return to the same line when you reopen a file.
if has("autocmd")
    au BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \ exe "normal! g'\"" |
        \ endif
endif

" }}}

" Backups {{{

set backup
set noswapfile

au BufWritePre * let &bex = '-' . substitute(expand('%:p:h'),'[\,/]','%','g') . strftime("(%d%m%y)%Hh%M") . '~' | " fixes backup//
" au BufWritePre * let &bex = '-' . strftime("%Y%m%d-%H%M%S") . '.vimbackup'

" }}}

" Search {{{

nnoremap / /\v
vnoremap / /\v

set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set gdefault

" Keep search in the middle
nnoremap n nzvzz
nnoremap N Nzvzz

" Not move when *
nnoremap * *<c-o>

noremap <leader><space> :noh<cr>:call clearmatches()<cr>

" Tab to match
map <tab> %

" Open a Quickfix window for the last search
nnoremap <silent> <leader>/ :execute 'vimgrep /'.@/.'/g %'<CR>:copen<CR>

" See next/prev
nnoremap <c-n> :cn<cr>
nnoremap <c-p> :cp<cr>

" Visual mode * {{{

function! s:VSetSearch()
    let temp = @@
    norm! gvy
    let @/ = '\V' . substitute(escape(@@, '\'), '\n', '\\n', 'g')
    let @@ = temp
endfunction

vnoremap * :<c-u>call <SID>VSetSearch()<CR>//<CR><c-o>
vnoremap # :<c-u>call <SID>VSetSearch()<CR>??<CR><c-o>

" }}}

" }}}

" Navigation {{{

" Easier to use
nnoremap H ^
nnoremap L g_

" split screen navigation
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l

" hhh cool
inoremap <c-a> <esc>I
inoremap <c-e> <esc>A

set virtualedit+=block

" }}}

" Yank to clipboard
vnoremap <c-c> "+y

" I Hate vim
vnoremap K k

" Increment ordered list
"inoremap <leader><cr> <esc>Yp<c-a>elC

" }}}
" Abbreviations {{{

" Emoticons
iabbrev ldis ಠ_ಠ
iabbrev lsad ಥ_ಥ
iabbrev lsmg ಸωಸ
iabbrev lflo (◕‿◕✿)

" }}}
