#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
sysxprofile=/etc/xprofile

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
userxprofile=$HOME/.config/X11/xprofile
userxprofilelocal=$HOME/.config/X11/xprofile.local


# merge in defaults and keymaps

[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"
[ -f "$sysxprofile" ] && . "$sysxprofile"

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userxprofilelocal" ] && . "$userxprofilelocal"
[ -f "$userxprofile" ] && . "$userxprofile"

#[ -f /etc/xsession ] && . /etc/xsession
#[ -f ~/.xsession ] && . ~/.xsession

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export XDG_SESSION_TYPE=x11

exec /usr/local/bin/dwm
