#!/bin/bash

source_if_exists() {
    if [ -s "$1" ] ; then
        source "$1"
    fi
}

source_if_exists "$XDG_CONFIG_HOME"/shell/aliases
source_if_exists "$XDG_CONFIG_HOME"/shell/aliases.local
source_if_exists "$XDG_CONFIG_HOME"/shell/shortcuts

# == PS1 ==
case "$USER" in
    waigni)  PS1='\[\e[0;97m\]w\[\e[38;5;250m\]a\[\e[38;5;245m\]i\[\e[38;5;81m\]g\[\e[38;5;45m\]n\[\e[38;5;39m\]i\[\e[1;97m\] \W \[\e[m\e(B\]' ;;
    root)   PS1='%s \[\e[0;91m\][root] \[\e[1;97m\]\W \[\e[m\e(B\]' ;;
    *)      PS1='\u \[\e[1;97m\]\W \[\e[m\e(B\]' ;;
esac
PS1="${PS1}${RANGER_LEVEL:+[ranger] }${SSH_TTY:+(ssh) }"

HISTFILE="$XDG_STATE_HOME"/bash_history
HISTSIZE=1000000

set completion-ignore-case on
set completion-query-items 200
set enable-keypad on
set page-completions off
set show-all-if-ambiguous on
set skip-completed-text on
set visible-stats on

set input-meta on
set output-meta on
set convert-meta off

# vi mode
set -o vi

# == pyenv ==
#if command -v pyenv >/dev/null ; then
#    eval "$(pyenv init - --no-rehash bash)" && \
#        eval "$(pyenv virtualenv-init - bash)"
#fi

source_if_exists "$XDG_CONFIG_HOME"/bash/bashrc.local
